### ISSUE TITLE
Add ability to import Caffe networks

### ISSUE THREAD

**Issue by alejandro-isaza** [aleph7/BrainCore#5]
I don't think we should add all of Protobuf but maybe have a script that converts a caffe prototxt into simpler format. Then have that simpler format be the standard BrainCore network definition format.

**Comment by aidangomez** [comment]
@aleph7 Are you thinking JSON? Or something even lighter? Take a look at msgpack.org

**Comment by alejandro-isaza** [comment]
I was thinking YAML

``` yaml
-
    name: ip1
    type: Inner Product
-
    name: relu1
    type: ReLU
    sources: [ip1]
```
